server:
  port: 8089   # free port for paid-status-service

spring:
  application:
    name: paid-status-service

  datasource:
    url: jdbc:mysql://localhost:3306/paidstatusdb
    username: zidio_admin
    password: YourNewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always