server:
  port: 8092

spring:
  application:
    name: fileupload-service

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB

  datasource:
    url: jdbc:mysql://localhost:3306/fileuploaddb
    username: root
    password: YourNewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: "ThisIsASecretKeyForJWTThatIsAtLeast32CharactersLongAndSecure"
  expiration-ms: 3600000   # 1 hour in milliseconds