server:
  port: 8083

spring:
  application:
    name: student-service

  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: root
    password: YourNewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:           #  fixed indentation (2 spaces under endpoint)
      show-details: always