# inside recruiter-service/src/main/resources/application.yml

server:
  port: 8085

spring:
  application:
    name: recruiter-service

  datasource:
    url: jdbc:mysql://localhost:3306/recruiterdb
    username: root
    password: YourNewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: "mySecretKey123"
  expiration-ms: 3600000   # 1 hour in milliseconds